installCRDs: true

replicaCount: 1

serviceAccount:

  create: true

  name: external-secrets

  annotations:

    eks.amazonaws.com/role-arn: arn:aws:iam::761018849945:role/enterprise-platform-dev-external-secrets-role