apiVersion: external-secrets.io/v1

kind: ExternalSecret

metadata:

  name: alertmanager-secret

spec:

  refreshInterval: {{ .Values.refreshInterval }}

  secretStoreRef:

    name: {{ .Values.secretStore.name }}

    kind: ClusterSecretStore

  target:

    name: {{ .Values.secrets.alertmanager.targetSecret }}

    creationPolicy: Owner

  data:

    - secretKey: smtp_host

      remoteRef:

        key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.alertmanager.awsSecret }}

        property: smtp_host

    - secretKey: smtp_username

      remoteRef:

        key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.alertmanager.awsSecret }}

        property: smtp_username

    - secretKey: smtp_password

      remoteRef:

        key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.alertmanager.awsSecret }}

        property: smtp_password

    - secretKey: smtp_from

      remoteRef:

        key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.alertmanager.awsSecret }}

        property: smtp_from