apiVersion: external-secrets.io/v1

kind: ExternalSecret

metadata:

  name: alertmanager-secret
  namespace: {{ .Values.secrets.alertmanager.namespace }}

spec:

  refreshInterval: {{ .Values.refreshInterval }}

  secretStoreRef:

    name: {{ .Values.secretStore.name }}

    kind: ClusterSecretStore

  target:

    name: {{ .Values.secrets.alertmanager.targetSecret }}

    creationPolicy: Owner

  data:
  - secretKey: smtp-host
    remoteRef:
      key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.alertmanager.awsSecret }}
      property: smtp-host

  - secretKey: smtp-port
    remoteRef:
      key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.alertmanager.awsSecret }}
      property: smtp-port

  - secretKey: smtp-username
    remoteRef:
      key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.alertmanager.awsSecret }}
      property: smtp-username

  - secretKey: smtp-password
    remoteRef:
      key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.alertmanager.awsSecret }}
      property: smtp-password