apiVersion: external-secrets.io/v1

kind: ExternalSecret

metadata:
  name: auth-service-secret
  namespace: {{ .Values.secrets.authService.namespace }}

spec:

  refreshInterval: {{ .Values.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: ClusterSecretStore

  target:
    name: {{ .Values.secrets.authService.targetSecret }}
    creationPolicy: Owner

  data:

    - secretKey: jwt-secret
      remoteRef:
        key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.authService.awsSecret }}
        property: jwt-secret

    - secretKey: database-username
      remoteRef:
        key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.authService.awsSecret }}
        property: database-username

    - secretKey: database-password
      remoteRef:
        key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.authService.awsSecret }}
        property: database-password

    - secretKey: database-url
      remoteRef:
        key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.authService.awsSecret }}
        property: database-url