apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: auth-service-app-secret
  namespace: {{ .Values.secrets.application.namespace }}

spec:

  refreshInterval: {{ .Values.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: ClusterSecretStore

  target:
    name: {{ .Values.secrets.application.targetSecret }}
    creationPolicy: Owner

  data:

    - secretKey: jwt-secret
      remoteRef:
        key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.application.awsSecret }}
        property: jwt-secret