apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: grafana-secret
  namespace: {{ .Values.secrets.grafana.namespace }}

spec:
  refreshInterval: {{ .Values.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: ClusterSecretStore

  target:
    name: {{ .Values.secrets.grafana.targetSecret }}
    creationPolicy: Owner

  data:
  - secretKey: username
    remoteRef:
      key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.grafana.awsSecret }}
      property: admin-user

  - secretKey: password
    remoteRef:
      key: {{ printf "%s/%s/%s" .Values.global.project .Values.global.environment .Values.secrets.grafana.awsSecret }}
      property: admin-password