apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:

  name: aws-load-balancer-controller

  namespace: argocd

  annotations:

    argocd.argoproj.io/sync-wave: "1"

spec:

  project: default

  sources:

    - repoURL: https://aws.github.io/eks-charts

      chart: aws-load-balancer-controller

      targetRevision: 1.13.0

      helm:

        valueFiles:

          - $values/charts/aws-load-balancer-controller/values.yaml

    - repoURL: git@github.com:Oluwole-Faluwoye/enterprise-platform-gitops.git

      targetRevision: main

      ref: values

  destination:

    server: https://kubernetes.default.svc

    namespace: kube-system

  syncPolicy:

    automated:

      prune: true

      selfHeal: true

    syncOptions:

      - CreateNamespace=true