{{- if and .Values.migration.enabled .Values.migration.artifact.key }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "auth-service.fullname" . }}-migration-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: {{ .Values.migration.databaseSecret.secretStore }}
    kind: ClusterSecretStore

  target:
    name: {{ .Values.migration.databaseSecret.name }}
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.database.credentialReference | quote }}
        property: username

    - secretKey: password
      remoteRef:
        key: {{ .Values.database.credentialReference | quote }}
        property: password
{{- end }}
