{{- if .Values.migration.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.migration.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.migration.serviceAccount.roleArn | quote }}
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: true
{{- end }}