groups:

  - name: application-recording-rules

    interval: 30s

    rules:

      #################################################
      # Deployment Availability
      #################################################

      - record: deployment:availability
        expr: |
          kube_deployment_status_replicas_available
          /
          kube_deployment_spec_replicas

      #################################################
      # Deployment Replica Ratio
      #################################################

      - record: deployment:replica_ratio
        expr: |
          kube_deployment_status_replicas_updated
          /
          kube_deployment_spec_replicas

      #################################################
      # Namespace CPU Usage
      #################################################

      - record: namespace:cpu_usage
        expr: |
          sum by (namespace)(
            rate(container_cpu_usage_seconds_total{
              container!="",
              image!=""
            }[5m])
          )

      #################################################
      # Namespace Memory Usage
      #################################################

      - record: namespace:memory_usage
        expr: |
          sum by (namespace)(
            container_memory_working_set_bytes{
              container!="",
              image!=""
            }
          )

      #################################################
      # Pod Restart Rate
      #################################################

      - record: pod:restart_rate
        expr: |
          increase(
            kube_pod_container_status_restarts_total[30m]
          )

      #################################################
      # HTTP Request Rate
      #################################################

      - record: application:http_requests_rate
        expr: |
          sum by (application) (
            rate(
              http_server_requests_seconds_count{
                application!=""
              }[5m]
            )
          )

      #################################################
      # HTTP 5xx Error Rate
      #################################################

      - record: application:http_5xx_rate
        expr: |
          (
            sum by (application) (
              rate(
                http_server_requests_seconds_count{
                  application!="",
                  status=~"5.."
                }[5m]
              )
            )
          )
          /
          (
            sum by (application) (
              rate(
                http_server_requests_seconds_count{
                  application!=""
                }[5m]
              )
            )
          )

      #################################################
      # HTTP Average Latency
      #################################################

      - record: application:http_latency_seconds
        expr: |
          (
            sum by (application) (
              rate(
                http_server_requests_seconds_sum{
                  application!=""
                }[5m]
              )
            )
          )
          /
          (
            sum by (application) (
              rate(
                http_server_requests_seconds_count{
                  application!=""
                }[5m]
              )
            )
          )

      #################################################
      # JVM Heap Usage
      #################################################

      - record: application:jvm_heap_usage
        expr: |
          (
            sum by (application) (
              jvm_memory_used_bytes{
                application!="",
                area="heap"
              }
            )
          )
          /
          (
            sum by (application) (
              jvm_memory_max_bytes{
                application!="",
                area="heap"
              }
            )
          )

      #################################################
      # Application CPU Usage
      #################################################

      - record: application:cpu_usage
        expr: |
          avg by (application) (
            process_cpu_usage{
              application!=""
            }
          )