groups:

  - name: storage-recording-rules

    interval: 30s

    rules:

      #################################################
      # PVC Storage Usage Ratio
      #################################################

      - record: pvc:storage_usage_ratio
        expr: |
          max by (namespace, persistentvolumeclaim) (
            kubelet_volume_stats_used_bytes
          )
          /
          max by (namespace, persistentvolumeclaim) (
            kubelet_volume_stats_capacity_bytes
          )

      #################################################
      # PVC Storage Used Bytes
      #################################################

      - record: pvc:storage_used_bytes
        expr: |
          max by (namespace, persistentvolumeclaim) (
            kubelet_volume_stats_used_bytes
          )

      #################################################
      # PVC Storage Capacity Bytes
      #################################################

      - record: pvc:storage_capacity_bytes
        expr: |
          max by (namespace, persistentvolumeclaim) (
            kubelet_volume_stats_capacity_bytes
          )