apiVersion: v1
kind: Secret

metadata:
  name: alertmanager-config
  namespace: monitoring

type: Opaque

stringData:
  alertmanager.yaml: |
{{ tpl (.Files.Get "alertmanager/config.yaml") . | indent 4 }}