apiVersion: v1
kind: ConfigMap

metadata:
  name: alertmanager-templates
  namespace: monitoring

  labels:
    app.kubernetes.io/name: monitoring-assets
    app.kubernetes.io/component: alertmanager

data:
  email.tmpl: |
{{ .Files.Get "alertmanager/templates/email.tmpl" | indent 4 }}