{{- range $path, $_ := .Files.Glob "grafana/datasources/*.yaml" }}

apiVersion: v1

kind: ConfigMap

metadata:

  name: grafana-datasource-{{ base $path | trimSuffix ".yaml" | lower }}

  namespace: monitoring

  labels:

    grafana_datasource: "1"

data:

  {{ base $path }}: |

{{ $.Files.Get $path | indent 4 }}

---

{{- end }}