{{- if .Values.prometheus.rules.enabled }}

{{- range $path, $_ := .Files.Glob "alerts/*.yaml" }}

{{- $content := $.Files.Get $path }}

{{- if trim $content }}

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ include "monitoring-assets.fullname" $ }}-{{ base $path | trimSuffix ".yaml" | lower }}
  namespace: {{ include "monitoring-assets.namespace" $ }}

  labels:
{{ include "monitoring-assets.labels" $ | indent 4 }}

    app.kubernetes.io/component: prometheus-rules
    release: prometheus-stack

spec:
{{ $content | indent 2 }}

---

{{- end }}

{{- end }}

{{- end }}