{{- range $path, $_ := .Files.Glob "recording-rules/*.yaml" }}

{{- $content := $.Files.Get $path }}

{{- if trim $content }}

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ include "monitoring-assets.fullname" $ }}-recording-{{ base $path | trimSuffix ".yaml" | lower }}
  namespace: {{ include "monitoring-assets.namespace" $ }}

  labels:
{{ include "monitoring-assets.labels" $ | indent 4 }}
    app.kubernetes.io/component: recording-rules

spec:
{{ $content | indent 2 }}

---

{{- end }}

{{- end }}