provider: aws

aws:
  region: us-east-1

domainFilters:
  - dreammyles.online

policy: sync

registry: txt

txtOwnerId: enterprise-platform

serviceAccount:
  create: true
  annotations: {}

sources:
  - ingress
  - service

interval: 1m

logLevel: info

triggerLoopOnEvent: true