namespace: monitoring

grafana:
  dashboards:
    enabled: true

  providers:
    enabled: true

  datasources:
    enabled: true

prometheus:
  servicemonitors:
    enabled: true

  rules:
    enabled: true

alertmanager:
  smtp:
    host: smtp-relay.brevo.com
    port: 587

####################################
# Global Settings
####################################

global:
  environment: dev

####################################
# Alert Defaults
####################################

alerts:
  enabled: true

  defaults:
    duration: 5m
    team: platform

####################################
# Notification Settings
####################################

notifications:
  email:
    enabled: false
    receiver: platform-team

  slack:
    enabled: false

  teams:
    enabled: false