defaultRules:
  create: true
  rules:
    kubeControllerManager: false
    kubeScheduler: false

grafana:
  enabled: true
  deploymentStrategy:
    type: Recreate
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/group.name: enterprise-platform
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:761018849945:certificate/de6a710c-c7ed-4c3d-84bc-1873b0848495
    hosts:
      - grafana.dev.dreammyles.online
    path: /
    pathType: Prefix
  admin:
    existingSecret: grafana-secret
    userKey: username
    passwordKey: password
  defaultDashboardsEnabled: false
  persistence:
    enabled: true
    storageClassName: gp3
    size: 10Gi
  service:
    type: ClusterIP
  securityContext:
    runAsNonRoot: true
    runAsUser: 472
    fsGroup: 472
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
      folder: /var/lib/grafana/dashboards
    datasources:
      enabled: true
      defaultDatasourceEnabled: false
      label: grafana_datasource
      labelValue: "1"
  plugins:
    - grafana-piechart-panel
################################################################################
# Prometheus
################################################################################
prometheus:
  prometheusSpec:
    retention: 15d
    retentionSize: 8GB
    walCompression: true
    externalLabels:
      cluster: devops-cluster
      environment: development
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 4Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
################################################################################
# Alertmanager
################################################################################
alertmanager:
  enabled: true
  namespaceOverride: monitoring
  alertmanagerSpec:
    replicas: 1
    retention: 120h
    configSecret: alertmanager-config
    secrets:
      - alertmanager-secret
    configMaps:
      - alertmanager-templates
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
