grafana:
  enabled: true

  deploymentStrategy:
    type: Recreate
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/group.name: enterprise-platform
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:761018849945:certificate/34825b11-fc08-4d5e-ad45-9b0a0ca323f0
    hosts:
      - grafana.dev.dreammyles.online
    path: /
    pathType: Prefix
  admin:
    existingSecret: grafana-secret
    userKey: username
    passwordKey: password
  defaultDashboardsEnabled: false
  persistence:
    enabled: true
    storageClassName: gp3
    size: 10Gi
  service:
    type: ClusterIP
  securityContext:
    runAsNonRoot: true
    runAsUser: 472
    fsGroup: 472
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
      folder: /var/lib/grafana/dashboards
    datasources:
      enabled: true
      defaultDatasourceEnabled: false
      label: grafana_datasource
      labelValue: "1"
  
  plugins:
    - grafana-piechart-panel
        
################################################################################
# Prometheus
################################################################################
prometheus:
  prometheusSpec:
    retention: 15d
    retentionSize: 8GB
    walCompression: true
    externalLabels:
      cluster: devops-cluster
      environment: development
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 4Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
################################################################################
# Alertmanager
################################################################################
alertmanager:
  enabled: true
  namespaceOverride: monitoring

  alertmanagerSpec:
    replicas: 1
    retention: 120h

    configSecret: alertmanager-config

    secrets:
      - alertmanager-secret

    configMaps:
      - alertmanager-templates

    containers:
      - name: alertmanager
        env:
          - name: SMTP_HOST
            valueFrom:
              secretKeyRef:
                name: alertmanager-secret
                key: smtp-host

          - name: SMTP_PORT
            valueFrom:
              secretKeyRef:
                name: alertmanager-secret
                key: smtp-port

          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                name: alertmanager-secret
                key: smtp-username

          - name: SMTP_FROM
            valueFrom:
              secretKeyRef:
                name: alertmanager-secret
                key: smtp-from

          - name: SMTP_TO
            valueFrom:
              secretKeyRef:
                name: alertmanager-secret
                key: smtp-to

    additionalArgs:
      - name: config.expand-env
        value: "true"

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi