# =========================================================
# INSTALL CRDs
# =========================================================

crds:

  enabled: true

# =========================================================
# PROMETHEUS
# =========================================================

prometheus:

  enabled: true

# =========================================================
# REPLICA COUNT
# =========================================================

replicaCount: 2

# =========================================================
# WEBHOOK
# =========================================================

webhook:

  replicaCount: 2

# =========================================================
# CA INJECTOR
# =========================================================

cainjector:

  replicaCount: 2