apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      timeInterval: 30s

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki.monitoring.svc.cluster.local:3100
    editable: false
    jsonData:
      maxLines: 5000

  - name: Alertmanager
    uid: alertmanager
    type: alertmanager
    access: proxy
    url: http://prometheus-stack-kube-prom-alertmanager.monitoring.svc.cluster.local:9093
    editable: false
    jsonData:
      implementation: prometheus