apiVersion: v1
kind: Secret

metadata:
  name: enterprise-platform-gitops
  namespace: argocd

  labels:
    argocd.argoproj.io/secret-type: repository

type: Opaque

stringData:
  type: git

  url: git@github.com:Oluwole-Faluwoye/enterprise-platform-gitops.git

  sshPrivateKey: REPLACE_AT_RUNTIME